name: debian publish

on:
  workflow_run:
    # Only run after all packaging is successful
    workflows: ["debian package"]
    types:
      - completed


jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Download Debian distribution artifacts
        uses: "actions/download-artifact@v2"
        with:
            name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-deb"
            path: "${{ github.workspace }}/dist"
