name: Upload Python Package to TestPyPI

on:
  workflow_run:
    # Only run after a successful Python build
    workflows: ["python-build"]
    pull_request:
      branches: [ "master" ]
    push:
      branches: [ "master" ]


jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Download Python distribution artifacts
        uses: "actions/download-artifact@v2"
        with:
            name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-py"
            path: "${{ github.workspace }}/dist"

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload --verbose --repository testpypi dist/*
