name: Build Test Python Release

on:
  push:
    branches:
      - "rework-deps"

jobs:
  deploy-python-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          ref: ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Upload to TestPyPI
        uses: casperdcl/deploy-pypi@v2
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          build: true
          upload: false
          # url: https://test.pypi.org/legacy/

      - name: Upload dist files
        uses: actions/upload-artifact@v2
        with:
          path: dist/
