name: Build ARM Packages on Commit to 'master'
# TODO: convert to latest commit as pre-release GitHub Release

on:
  push:
    branches: [ "master", "ci-test-build-arm-*" ]

jobs:
  build-debian:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target_arch: ["armhf", "arm64"]
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Debian Docker container for changelog patching
        run: |
          docker create --name chglog --volume ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }}/ --tty pitop/gbp-dch-gen:latest sleep inf
          docker start chglog
          docker exec chglog git config --global user.name "pi-top"
          docker exec chglog git config --global user.email "deb-maintainers@pi-top.com"

      - name: Get latest version tag ID
        id: get_latest_version_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get latest version tag commit
        id: get_latest_version_tag_commit
        run: |
          ls -la
          LATEST_TAG_COMMIT=$(git show-ref -s ${{ steps.get_latest_version_tag.outputs.tag }})
          echo "::set-output name=latest_version_tag_commit::$LATEST_TAG_COMMIT"

      - name: Patch changelog (snapshot)
        run: |
          docker exec chglog gbp dch --verbose --git-author --ignore-branch --snapshot \
            --since=${{ steps.get_latest_version_tag_commit.outputs.latest_version_tag_commit }}
        # --snapshot-number=$(git rev-list --count ${{ steps.get_latest_version_tag_commit.outputs.latest_version_tag_commit }}..HEAD)

      - name: Show updated changelog
        run: |
          cat debian/changelog

      - name: Build Debian package
        uses: pi-top/action-debian-package@v0.2.2
        with:
          source_directory: "${{ github.workspace }}"
          artifacts_directory: "${{ github.workspace }}/artifacts/bin"

          docker_image: "pitop/deb-build:latest"
          distribution: "buster-backports"
          target_architecture: ${{ matrix.target_arch }}

          lintian_opts: "--dont-check-part nmu --no-tag-display-limit --display-info --show-overrides --fail-on error --fail-on warning --fail-on info"
          # Package uses latest packaging syntax and Lintian opts/tags
          dpkg_buildpackage_opts: "--no-sign --no-check-builddeps --post-clean"

      - name: Separate Debian source package files from binary
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/src/
          mv ${{ github.workspace }}/artifacts/bin/* ${{ github.workspace }}/artifacts/src/
          mv ${{ github.workspace }}/artifacts/src/*.deb ${{ github.workspace }}/artifacts/bin/

      - name: Upload Debian source package files
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-${{ matrix.target_arch }}-deb-src"
          path: "${{ github.workspace }}/artifacts/src/"

      - name: Upload Debian binary packages
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-${{ matrix.target_arch }}-deb"
          path: "${{ github.workspace }}/artifacts/bin/"
