name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target_arch: ["armhf", "arm64"]
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1
        with:
          repository: "pi-top/pi-top-Python-SDK"
          latest: true
          # fileName: "python3-pitop_${{ github.ref }}_${{ matrix.target_arch }}.deb"
          tarBall: true

      # TODO: untar release

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload --verbose dist/*

      # TODO: publish to apt repository
