name: pi-topOS Docker Base Image Build

on:
  workflow_dispatch:
  push:
    paths:
      - "tests/Dockerfile"
      - "tests/requirements.txt"
      - ".github/workflows/test-runner-docker-builder.yml"

env:
  IMAGE_NAME: "pitop/sdk-test-runner"
  PLATFORMS: "linux/amd64"

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=branch

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: tests
          file: tests/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
